apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: qa
  name: gcp-nginx-pvc
spec:
  storageClassName: storageclass-qa-nginx
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi