apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: qa
  name: sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: sa-qa
  namespace: qa
